import { useState } from "react";
import type { Register } from "@/lib/supabase";

const AGE_BUCKETS = ["under 25", "25-40", "40-60", "60+"] as const;
const REGISTERS: { value: Register; label: string }[] = [
  { value: "academic", label: "Academic" },
  { value: "business", label: "Business" },
  { value: "journalism", label: "Journalism" },
  { value: "marketing", label: "Marketing" },
  { value: "creative", label: "Creative" },
  { value: "casual", label: "Casual" },
  { value: "other", label: "Other" },
];

export interface OnboardingResult {
  age_bucket: string | null;
  primary_register: Register | null;
}

export function Onboarding({ onDone }: { onDone: (r: OnboardingResult) => void }) {
  const [age, setAge] = useState<string | null>(null);
  const [reg, setReg] = useState<Register | null>(null);

  return (
    <div className="mx-auto flex min-h-[100dvh] max-w-md flex-col justify-center px-6 py-10 fade-in">
      <h1 className="font-serif text-3xl leading-tight text-foreground">Human or AI?</h1>
      <p className="mt-2 text-sm text-muted-foreground">A perception game for the LLM era.</p>

      <div className="mt-6 space-y-3 text-[15px] leading-relaxed text-foreground">
        <p>
          You'll see <span className="font-medium">30 short phrases</span>, one at a time. Some were written
          by humans. Some were generated by AI.
        </p>
        <p className="text-muted-foreground">
          Your job: trust your gut and call each one. We'll tally your score and show you how sharp your
          ear really is.
        </p>
      </div>

      <div className="mt-8 rounded-xl border border-border bg-card p-5">
        <p className="text-sm text-card-foreground">
          First — a couple of optional questions so we can show you how you stack up against others like you.
        </p>

        <div className="mt-6">
          <div className="mb-2 text-xs font-medium uppercase tracking-wide text-muted-foreground">Age</div>
          <div className="grid grid-cols-2 gap-2">
            {AGE_BUCKETS.map((b) => (
              <button
                key={b}
                onClick={() => setAge((cur) => (cur === b ? null : b))}
                className={`rounded-lg border px-3 py-2 text-sm transition-colors ${
                  age === b
                    ? "border-foreground bg-foreground text-background"
                    : "border-border bg-background text-foreground hover:bg-accent"
                }`}
              >
                {b}
              </button>
            ))}
          </div>
        </div>

        <div className="mt-5">
          <div className="mb-2 text-xs font-medium uppercase tracking-wide text-muted-foreground">
            Primary writing register
          </div>
          <div className="flex flex-wrap gap-2">
            {REGISTERS.map((r) => (
              <button
                key={r.value}
                onClick={() => setReg((cur) => (cur === r.value ? null : r.value))}
                className={`rounded-full border px-3 py-1.5 text-sm transition-colors ${
                  reg === r.value
                    ? "border-foreground bg-foreground text-background"
                    : "border-border bg-background text-foreground hover:bg-accent"
                }`}
              >
                {r.label}
              </button>
            ))}
          </div>
        </div>
      </div>

      <div className="mt-6 grid grid-cols-2 gap-3">
        <button
          onClick={() => onDone({ age_bucket: null, primary_register: null })}
          className="rounded-xl border border-border bg-background px-4 py-3 text-base font-medium text-foreground hover:bg-accent"
        >
          Skip & play
        </button>
        <button
          onClick={() => onDone({ age_bucket: age, primary_register: reg })}
          className="rounded-xl border border-foreground bg-foreground px-4 py-3 text-base font-medium text-background hover:opacity-90"
        >
          Start game
        </button>
      </div>
    </div>
  );
}
